In [2]:
import numpy as np 
import pandas as pd 

In [3]:
data = pd.read_csv('dataset.csv')

In [4]:
data.sample()

A1_Score[Social_communication]  A2_Score[restrictive]   \
16                               1                       0   

    A3_Score[excellency]   A4_Score[sensory_issues]   A5_Score[aggression]   \
16                      0                          0                      0   

    A6_Score[hyperactivity]  A7_Score[attention_problem]   A8_Score[anxiety]   \
16                        0                             1                   1   

    A9_Score[depression]   A10_Score[irritability]  ... gender  \
16                      1                        1  ...      m   

            Ethnicity Jundice Austim  contry_of_res used_app_before  \
16  'Middle Eastern '      no      no        Jordan              no   

   result_numeric      age_desc  relation asd  
16              5  '18 and more'     Self  NO  

[1 rows x 21 columns]

In [5]:
data.head()

A1_Score[Social_communication]  A2_Score[restrictive]   \
0                               1                       1   
1                               1                       1   
2                               1                       1   
3                               1                       1   
4                               1                       0   

   A3_Score[excellency]   A4_Score[sensory_issues]   A5_Score[aggression]   \
0                      1                          1                      0   
1                      0                          1                      0   
2                      0                          1                      1   
3                      0                          1                      0   
4                      0                          0                      0   

   A6_Score[hyperactivity]  A7_Score[attention_problem]   A8_Score[anxiety]   \
0                        0                             1                   1   
1                        0                             0                   1   
2                        0                             1                   1   
3                        0                             1                   1   
4                        0                             0                   1   

   A9_Score[depression]   A10_Score[irritability]  ... gender       Ethnicity  \
0                      0                        0  ...      f  White-European   
1                      0                        1  ...      m          Latino   
2                      1                        1  ...      m          Latino   
3                      0                        1  ...      f  White-European   
4                      0                        0  ...      f               ?   

  Jundice Austim     contry_of_res used_app_before result_numeric  \
0      no      no  'United States'              no              6   
1      no     yes           Brazil              no              5   
2     yes     yes            Spain              no              8   
3      no     yes  'United States'              no              6   
4      no      no            Egypt              no              2   

       age_desc  relation  asd  
0  '18 and more'     Self   NO  
1  '18 and more'     Self   NO  
2  '18 and more'   Parent  YES  
3  '18 and more'     Self   NO  
4  '18 and more'        ?   NO  

[5 rows x 21 columns]

In [6]:
data.shape


(717, 21)

In [7]:
data.info

<bound method DataFrame.info of      A1_Score[Social_communication]  A2_Score[restrictive]   \
0                                 1                       1   
1                                 1                       1   
2                                 1                       1   
3                                 1                       1   
4                                 1                       0   
..                              ...                     ...   
712                               1                       0   
713                               1                       0   
714                               1                       1   
715                               1                       1   
716                               0                       1   

     A3_Score[excellency]   A4_Score[sensory_issues]   A5_Score[aggression]   \
0                        1                          1                      0   
1                        0                         

In [8]:
data.columns

Index(['A1_Score[Social_communication]', 'A2_Score[restrictive] ',
       'A3_Score[excellency] ', 'A4_Score[sensory_issues] ',
       'A5_Score[aggression] ', 'A6_Score[hyperactivity]',
       'A7_Score[attention_problem] ', 'A8_Score[anxiety] ',
       'A9_Score[depression] ', 'A10_Score[irritability]', 'age', 'gender',
       'Ethnicity', 'Jundice', 'Austim ', 'contry_of_res', 'used_app_before',
       'result_numeric', 'age_desc ', 'relation', 'asd'],
      dtype='object')

ID - ID of the patient

A1_Score to A10_Score - Score based on Autism Spectrum Quotient (AQ) 10 item screening tool

age - Age of the patient in years

gender - Gender of the patient

ethnicity - Ethnicity of the patient

jaundice - Whether the patient had jaundice at the time of birth

autism - Whether an immediate family member has been diagnosed with autism

contry_of_res - Country of residence of the patient

used_app_before - Whether the patient has undergone a screening test before

result - Score for AQ1-10 screening test

age_desc - Age of the patient

relation - Relation of patient who completed the test

Class/ASD - Classified result as 0 or 1. Here 0 represents No and 1 represents Yes. This is the target column, and during submission submit the values as 0 or 1 only.

In [9]:
#excuding the columns that are repeating and do not contribute to the project prediction
data=data[['A1_Score[Social_communication]', 'A2_Score[restrictive] ','A3_Score[excellency] ', 
           'A4_Score[sensory_issues] ','A5_Score[aggression] ', 'A6_Score[hyperactivity]',
           'A7_Score[attention_problem] ', 'A8_Score[anxiety] ',
       'A9_Score[depression] ', 'A10_Score[irritability]', 'age', 'gender',
        'Jundice', 'Austim ', 'used_app_before','asd']]

In [10]:
data.isnull().sum()

A1_Score[Social_communication]    0
A2_Score[restrictive]             0
A3_Score[excellency]              0
A4_Score[sensory_issues]          0
A5_Score[aggression]              0
A6_Score[hyperactivity]           0
A7_Score[attention_problem]       0
A8_Score[anxiety]                 0
A9_Score[depression]              0
A10_Score[irritability]           0
age                               0
gender                            0
Jundice                           0
Austim                            0
used_app_before                   0
asd                               0
dtype: int64

In [11]:
data=data.drop_duplicates()

In [12]:
question_mark_count = (data == '?').sum().sum()
print(question_mark_count)

2


In [13]:
data = data.replace('?', pd.NA).dropna()

In [14]:
data['gender'].unique()

array(['f', 'm'], dtype=object)

In [15]:
data['Jundice'].unique()

array(['no', 'yes'], dtype=object)

In [16]:
data['Austim '].unique()

array(['no', 'yes'], dtype=object)

In [17]:
data['used_app_before'].unique()

array(['no', 'yes'], dtype=object)

In [18]:
data['asd'].unique()

array(['NO', 'YES'], dtype=object)

In [19]:
data['gender'] = data['gender'].map({'m': 0, 'f': 1})  
data['Jundice'] = data['Jundice'].map({'yes': 1, 'no': 0}) 
data['Austim '] = data['Austim '].map({'yes': 1, 'no': 0})  
data['used_app_before'] = data['used_app_before'].map({'yes': 1, 'no': 0})  
data['asd'] = data['asd'].map({'NO': 0, 'YES': 1}) 
# Check if there are any NaN values after mapping
print("NaN values in the dataset:")
print(data.isna().sum())

NaN values in the dataset:
A1_Score[Social_communication]    0
A2_Score[restrictive]             0
A3_Score[excellency]              0
A4_Score[sensory_issues]          0
A5_Score[aggression]              0
A6_Score[hyperactivity]           0
A7_Score[attention_problem]       0
A8_Score[anxiety]                 0
A9_Score[depression]              0
A10_Score[irritability]           0
age                               0
gender                            0
Jundice                           0
Austim                            0
used_app_before                   0
asd                               0
dtype: int64


In [20]:
data.sample()

A1_Score[Social_communication]  A2_Score[restrictive]   \
42                               0                       0   

    A3_Score[excellency]   A4_Score[sensory_issues]   A5_Score[aggression]   \
42                      1                          1                      0   

    A6_Score[hyperactivity]  A7_Score[attention_problem]   A8_Score[anxiety]   \
42                        0                             0                   0   

    A9_Score[depression]   A10_Score[irritability] age  gender  Jundice  \
42                      0                        1  34       1        0   

    Austim   used_app_before  asd  
42        1                0    0

In [21]:
# Defining the features (X) and the target variable (y)
X = data.drop(['asd'], axis=1)
y = data['asd']

In [22]:
# Split the dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

In [23]:
from sklearn.preprocessing import StandardScaler
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
# Train and evaluate Logistic Regression model
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)
y_pred_lr = lr_model.predict(X_test)
print("Logistic Regression:")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Classification Report:")
print(classification_report(y_test, y_pred_lr))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr))

Logistic Regression:
Accuracy: 0.9927536231884058
Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       106
           1       1.00      0.97      0.98        32

    accuracy                           0.99       138
   macro avg       1.00      0.98      0.99       138
weighted avg       0.99      0.99      0.99       138

Confusion Matrix:
[[106   0]
 [  1  31]]


In [25]:
from sklearn.tree import DecisionTreeClassifier

# Train and evaluate Decision Tree Classifier model
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)
print("Decision Tree Classifier:")
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Classification Report:")
print(classification_report(y_test, y_pred_dt))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

Decision Tree Classifier:
Accuracy: 0.9057971014492754
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.92      0.94       106
           1       0.77      0.84      0.81        32

    accuracy                           0.91       138
   macro avg       0.86      0.88      0.87       138
weighted avg       0.91      0.91      0.91       138

Confusion Matrix:
[[98  8]
 [ 5 27]]


In [26]:
from sklearn.ensemble import RandomForestClassifier
# Train and evaluate Random Forest Classifier model
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)
print("Random Forest Classifier:")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Classification Report:")
print(classification_report(y_test, y_pred_rf))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))


Random Forest Classifier:
Accuracy: 0.9565217391304348
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       106
           1       0.96      0.84      0.90        32

    accuracy                           0.96       138
   macro avg       0.96      0.92      0.94       138
weighted avg       0.96      0.96      0.96       138

Confusion Matrix:
[[105   1]
 [  5  27]]


In [27]:
from sklearn.svm import SVC
# Train and evaluate Support Vector Machine model
svm_model = SVC()
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)
print("Support Vector Machine:")
print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print("Classification Report:")
print(classification_report(y_test, y_pred_svm))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))

Support Vector Machine:
Accuracy: 0.9710144927536232
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       106
           1       0.97      0.91      0.94        32

    accuracy                           0.97       138
   macro avg       0.97      0.95      0.96       138
weighted avg       0.97      0.97      0.97       138

Confusion Matrix:
[[105   1]
 [  3  29]]


In [28]:
import pickle
pickle.dump(lr_model,open('asd.pkl','wb'))

In [29]:
final_model = pickle.load(open('asd.pkl','rb'))

In [30]:
pred=final_model.predict(X_test)

In [31]:
print("Accuracy:", accuracy_score(y_test,pred))

Accuracy: 0.9927536231884058


In [37]:
selected_val1 = input("Social Communication - Do you find it difficult to start conversations with people you don’t know well? yes/no ")
selected_val2 = input("Restrictive Behaviors -  Are there specific sounds or lights that you find overwhelming? yes/no")
selected_val3 = input("excellency - Do you have any specific interests or activities that you focus on intensely? yes/no")
selected_val4 = input("Sensory Issues - Are there specific sounds or lights that you find overwhelming? yes/no")
selected_val5 = input("Aggression - Do you often find it hard to manage feelings of frustration or anger? yes/no")
selected_val6 = input("Hyperactivity - Do you find it challenging to stay still or calm for extended periods? yes/no")
selected_val7 = input("Attention Problems - Do you have difficulty staying focused on tasks for a long time? yes/no")
selected_val8 = input("Anxiety - Do you often feel anxious in certain situations or events? yes/no")
selected_val9 = input("Depression - Do you frequently experience feelings of sadness? yes/no")
selected_val10 = input("Irritability - Do you get irritable in response to specific situations or events? yes/no")
selected_val_age = int(input("Enter your age:"))
selected_val_gender = input("Male/Female  gender - Gender of the patient")
selected_val_jaundice = input("jaundice - Whether the you had jaundice at the time of birth yes/no")
selected_val_autism = input("autism - Whether an immediate family member has been diagnosed with autism yes/no")
selected_val_app = input("used_app_before - Whether the patient has undergone a screening test before yes/no")
data = [selected_val1, selected_val2, selected_val3, selected_val4, selected_val5, selected_val6, selected_val7, selected_val8,selected_val9, selected_val10, selected_val_age, selected_val_gender, selected_val_jaundice, selected_val_autism, selected_val_app]
dict1 = {"yes": 1, "no": 0, "Male": 0, "Female": 1}
def map_values(data, dict1):
    return [dict.get(item, item) for item in data]
data = map_values(data, dict1)
data = np.array(data)
data = data.reshape(1,-1)
prediction = lr_model.predict(data)
final_prediction = int(prediction.item() )

if final_prediction==0:
    print("The test indicates that you don't have Autism Specturm Disorder")
else:
    print("The test indicates that you  have Autism Spectrum Disorder")



Social Communication - Do you find it difficult to start conversations with people you don’t know well? yes/no  no
Restrictive Behaviors -  Are there specific sounds or lights that you find overwhelming? yes/no no
excellency - Do you have any specific interests or activities that you focus on intensely? yes/no no
Sensory Issues - Are there specific sounds or lights that you find overwhelming? yes/no no
Aggression - Do you often find it hard to manage feelings of frustration or anger? yes/no no
Hyperactivity - Do you find it challenging to stay still or calm for extended periods? yes/no no
Attention Problems - Do you have difficulty staying focused on tasks for a long time? yes/no no
Anxiety - Do you often feel anxious in certain situations or events? yes/no no
Depression - Do you frequently experience feelings of sadness? yes/no no
Irritability - Do you get irritable in response to specific situations or events? yes/no no
Enter your age: 1
Male/Female  gender - Gender of the patient Ma

The test indicates that you don't have Autism Specturm Disorder
